//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.GameServer"/> </summary
    public sealed class GameServerClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public GameServerClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "GameServer";
            }
        }
        
        /// <summary>
        /// Call the NewCharacter method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.NewCharacter"/>
        /// </summary>
        public Beamable.Common.Promise<string> NewCharacter(string claudeContext)
        {
            string serialized_claudeContext = this.SerializeArgument<string>(claudeContext);
            string[] serializedFields = new string[] {
                    serialized_claudeContext};
            return this.Request<string>("GameServer", "character/new", serializedFields);
        }
        
        /// <summary>
        /// Call the GetCharacter method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.GetCharacter"/>
        /// </summary>
        public Beamable.Common.Promise<CharacterView> GetCharacter()
        {
            string[] serializedFields = new string[0];
            return this.Request<CharacterView>("GameServer", "character/get", serializedFields);
        }
        
        /// <summary>
        /// Call the StartAdventure method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.StartAdventure"/>
        /// </summary>
        public Beamable.Common.Promise<string> StartAdventure(string history, string prompt)
        {
            string serialized_history = this.SerializeArgument<string>(history);
            string serialized_prompt = this.SerializeArgument<string>(prompt);
            string[] serializedFields = new string[] {
                    serialized_history,
                    serialized_prompt};
            return this.Request<string>("GameServer", "adventure/start", serializedFields);
        }
        
        /// <summary>
        /// Call the TestClaude method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.TestClaude"/>
        /// </summary>
        public Beamable.Common.Promise<string> TestClaude(string prompt)
        {
            string serialized_prompt = this.SerializeArgument<string>(prompt);
            string[] serializedFields = new string[] {
                    serialized_prompt};
            return this.Request<string>("GameServer", "claude", serializedFields);
        }
        
        /// <summary>
        /// Call the TestScenario method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.TestScenario"/>
        /// </summary>
        public Beamable.Common.Promise<string> TestScenario(string prompt)
        {
            string serialized_prompt = this.SerializeArgument<string>(prompt);
            string[] serializedFields = new string[] {
                    serialized_prompt};
            return this.Request<string>("GameServer", "scenario", serializedFields);
        }
        
        /// <summary>
        /// Call the TestBlockade method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.TestBlockade"/>
        /// </summary>
        public Beamable.Common.Promise<string> TestBlockade(string prompt)
        {
            string serialized_prompt = this.SerializeArgument<string>(prompt);
            string[] serializedFields = new string[] {
                    serialized_prompt};
            return this.Request<string>("GameServer", "blockade", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersGameServerClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForGameServerClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<GameServerClient>();
        }
        
        public static GameServerClient GameServer(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<GameServerClient>();
        }
    }
}
